stages:
  - build
  - test

build:
  stage: build
  script: 
    - echo "Executing build stage"
    - cd


test: 
  stage: test
  script:
    - echo "Executing test stage"
    - mkdir hello_world_gitlab